name: flutter_template
description: A new Flutter application for router.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.0+15

environment:
  sdk: ">=2.17.3 <3.4.0"

dependencies:
  flutter:
    sdk: flutter
  # 图标库
  font_awesome_flutter: ^10.1.0
  # 加载动画
  flutter_spinkit: ^5.1.0
  # 虚线边框
  dotted_border: ^2.0.0+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # http
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  # 路径
  path_provider: ^2.0.11
  # 提示
  oktoast: ^3.2.0
  # 简单数据存储
  shared_preferences: ^2.0.15
  # 路由管理 & 状态管理
  get: ^4.6.5
  # 轮播图
  card_swiper: ^3.0.0
  # 屏幕尺寸
  flutter_screenutil: ^5.9.0
  # 提示条数
  badges: ^2.0.3
  # url 处理 打开网页、打电话、发邮件等
  url_launcher: ^6.1.3
  # 上拉下拉刷新
  pull_to_refresh_flutter3: ^2.0.1
  # 日期格式化
  date_format: ^2.0.6
  # html 处理
  flutter_html: ^3.0.0-alpha.5
  # 获取版本信息
  package_info_plus: ^4.0.2
  # 图片选择 -- 头像上传
  image_picker: ^1.0.7
  # 权限
  permission_handler: ^10.0.0
  # 文件选择器
  file_picker: ^5.0.0
  # # 视频流
  # fijkplayer: ^0.10.1
  # wakelock: ^0.6.2
  # css滤镜效果
  css_filter: ^1.0.2
  # 轮播图空异常版
  flutter_swiper_null_safety: ^1.0.2
  # 国际化
  flutter_localization: ^0.1.13
  intl: ^0.18.0
  intl_generator: ^0.4.1
  # AES加密
  encrypt: ^5.0.1
  # 时间选择
  day_night_time_picker: ^1.2.0
  # wifi信息获取
  # wifi_info_plugin_plus: ^2.0.2
  #网络监测
  connectivity_plus: ^5.0.2
  # 震动的插件
  vibration: ^1.7.7
  # 获取mac地址(暂时去掉)
  #  mac_address: ^1.0.0
  #选择时间
  progressive_time_picker: ^0.0.9
  # 身份验证
  local_auth: ^2.1.8
  # 设备信息
  device_info_plus: ^8.0.0
  # wifi信息
  network_info_plus: ^4.0.1
  # 加载网络图片
  cached_network_image: ^3.1.0
  time_picker_sheet_fork: ^0.0.3
  # 定位
  location: ^5.0.0
  # 反地理编码
  geocode: 1.0.3
  web_socket_channel: ^2.4.0
  mqtt_client: ^10.0.0
  event_bus: ^2.0.0
  pie_chart: ^5.4.0
  d_chart: ^2.6.3
  easy_pie_chart: ^1.0.0
  intl_phone_field: ^3.2.0
  dropdown_button2: ^2.3.9
  flutter_spinner_time_picker: ^0.2.1
  flutter_switch: ^0.3.2
  webview_flutter: ^4.5.0
  flutter_internet_speed_test: ^1.5.0
  flutter_progress_hud: ^2.0.2
  logger: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.0
  # web_socket_channel: ^2.2.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_intl:
  enabled: true
